name: Deploy to Oracle Cloud

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: oracle-cloud
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BITRISE_API_KEY: ${{ secrets.BITRISE_API_KEY }}
          envkey_GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.ORACLE_CLOUD_SSH_HOST }}
          ssh_private_key: ${{ secrets.ORACLE_CLOUD_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.ORACLE_CLOUD_SSH_USER }}
          docker_compose_prefix: manager
